# Generated by Django 2.2.10 on 2020-09-09 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagebanner',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 9, 17, 35, 50, 431050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homesidebanner',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 9, 17, 35, 57, 393798, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopbottombanner',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 9, 17, 36, 3, 653579, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoptopbanner',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 9, 9, 17, 36, 11, 230876, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
