# Generated by Django 2.2.10 on 2020-09-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200909_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptopbanner',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shoptopbanner',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
