# Generated by Django 2.2.10 on 2020-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
