# Generated by Django 2.2.10 on 2020-09-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_slider_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, choices=[('Black', 'Black'), ('White', 'White'), ('Red', 'Red'), ('Pink', 'Pink'), ('Green', 'Green'), ('Purple', 'Purple'), ('Brown', 'Brown')], max_length=1000, null=True),
        ),
    ]
