# Generated by Django 2.2.10 on 2020-10-01 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201001_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='style',
            new_name='size_chart',
        ),
    ]
